//create category
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";

//create Event
export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const CLEAR_EVENT_ERROR = "CLEAR_EVENT_ERROR";
export const CLEAR_EVENT_SUCCESS = "CLEAR_EVENT_SUCCESS";

//Post
//create post category
export const CREATE_PCAT_REQUEST = "CREATE_PCAT_REQUEST";
export const CREATE_PCAT_SUCCESS = "CREATE_PCAT_SUCCESS";
export const CREATE_PCAT_FAIL = "CREATE_PCAT_FAIL";

//create Post
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
//update post
export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";
//delete post
export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const CLEAR_POST_ERROR = "CLEAR_POST_ERROR";
export const CLEAR_POST_SUCCESS = "CLEAR_POST_SUCCESS";

//participation
//get all parts
export const GET_PARTS_REQUEST = "GET_PARTS_REQUEST";
export const GET_PARTS_SUCCESS = "GET_PARTS_SUCCESS";
export const GET_PARTS_FAIL = "GET_PARTS_FAIL";
//delete part
export const DELETE_PART_REQUEST = "DELETE_PART_REQUEST";
export const DELETE_PART_SUCCESS = "DELETE_PART_SUCCESS";
export const DELETE_PART_FAIL = "DELETE_PART_FAIL";

//users
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

//Donation
//get all donation> admin
export const GET_DONATOIN_REQUEST = "GET_DONATOIN_REQUEST";
export const GET_DONATOIN_SUCCESS = "GET_DONATOIN_SUCCESS";
export const GET_DONATOIN_FAIL = "GET_DONATOIN_FAIL";
