export const MEET_REGISTER_REQUEST = "MEET_REGISTER_REQUEST";
export const MEET_REGISTER_SUCCESS = "MEET_REGISTER_SUCCESS";
export const MEET_REGISTER_FAIL = "MEET_REGISTER_FAIL";

export const MEET_LIST_REQUEST = "MEET_LIST_REQUEST";
export const MEET_LIST_SUCCESS = "MEET_LIST_SUCCESS";
export const MEET_LIST_FAIL = "MEET_LIST_FAIL";
